### ISSUE TITLE
Analise do HTML feito em sala de aula.

### ISSUE THREAD

**Issue by MOVelasco** [Eduardolinsmotta/EstudoSalaDeAula#1]
Olá Eduardo.

Não estou vendo aqui, no seu repositório o arquivo que fizemos em sala de aula.
O que houve? Teve problemas para subir o arquivo?
Esta com alguma dificuldade no Git ou Github ?

Me da um retorno.

**Comment by Eduardolinsmotta** [comment]
Olá, Professor.

Já subi o repositório aqui no Github
